### ISSUE TITLE
Comparison to fastmod

### ISSUE THREAD

**Issue by dwijnand** [SuperTanker/ruplacer#19]
Hey.  Interesting project.  I wondered: are you aware of https://github.com/facebookincubator/fastmod?  It seems to have a similar goal as your project and is also written in Rust.  I wondered if you wanted to include a comparison to it (somewhere).

**Comment by dmerejkowsky** [comment]
Good suggestion.

I did not know about `fastmod` so I installed it and ran it a few times. Here's a  list of differences I've seen so far:

* fastmod is interactive by default, ruplacer is not
* Interactive display is nice (and the edit feature is cool) but then you can't see the whole diff at once
* Small bug: If the same word is changed 3 times on the same line, the diff is shown 3 times
* You can accept all diffs but then you don't see what changed

The equivalent to `--go` is `--accept-all --print-changed-files` and it only display the files that changed, not the diff.

ruplacer has `--subvert`, fastmod does not
fastmod has `--multiline`, ruplacer does not

fastmod can use several CPUs when 'fast mode' is used. Not really sure there's a bottleneck there, need to make some measurements

There are a few more flags in fastmod to select which files to run like `--glob` or `--extensions`.


Hope this helps!

**Comment by dwijnand** [comment]
Lovely.  Thanks!
