### ISSUE TITLE
Diff preview is suboptimal

### ISSUE THREAD

**Issue by blastrock** [SuperTanker/ruplacer#4]
When replacing trustchain by blockchain, we can get the following preview

```
--   trustchain_creation: 0,
++   blockchain_creation: 0,
```

Obtained result: `trustchain_creation:` is completely highlighted
Expected result: only the `trustchain` part should be highlighted, without the `_creation:`

**Comment by dmerejkowsky** [comment]
Fixed in e65aea5128b750e5461c9614bfba061032617fad
